from __future__ import annotations

import argparse
import csv
import json
import shutil
import sys
from pathlib import Path
from typing import Any

if __package__ in (None, ""):
    sys.path.append(str(Path(__file__).resolve().parents[1]))

from src.config import DEFAULT_OUTPUT_DIR, PROJECT_ROOT  # noqa: E402
from src.utils.export import write_json  # noqa: E402


DEFAULT_FINAL_DIR = PROJECT_ROOT / "data" / "final"

FINAL_SHOT_FIELDS = [
    "shot_id",
    "shot_type",
    "timestamp",
    "frame",
    "player_track_id",
    "player_side",
    "event_confidence",
    "ball_track_id",
    "nearest_racket_track_id",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Package pipeline work files into assignment-facing final outputs."
    )
    parser.add_argument(
        "--outputs-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Pipeline outputs directory. Default: {DEFAULT_OUTPUT_DIR}",
    )
    parser.add_argument(
        "--final-dir",
        type=Path,
        default=DEFAULT_FINAL_DIR,
        help=f"Final packaged output directory. Default: {DEFAULT_FINAL_DIR}",
    )
    return parser.parse_args()


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def require_file(path: Path) -> None:
    if not path.exists():
        raise FileNotFoundError(f"Required pipeline output is missing: {path}")


def safe_player_id(shot: dict[str, Any]) -> str | int:
    player_id = shot.get("player_track_id")
    return "unknown" if player_id in (None, "") else player_id


def final_shot_record(shot: dict[str, Any]) -> dict[str, Any]:
    return {
        "shot_id": shot["shot_id"],
        "shot_type": shot["shot_type"],
        "timestamp": shot["timestamp"],
        "frame": shot["frame"],
        "player_track_id": safe_player_id(shot),
        "player_side": shot.get("player_side", "unknown"),
        "event_confidence": shot["event_confidence"],
        "ball_track_id": shot.get("ball_track_id"),
        "nearest_racket_track_id": shot.get("nearest_racket_track_id"),
    }


def write_final_csv(shots: list[dict[str, Any]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=FINAL_SHOT_FIELDS)
        writer.writeheader()
        for shot in shots:
            writer.writerow(final_shot_record(shot))


def copy_required(src: Path, dst: Path) -> None:
    require_file(src)
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def build_final_payload(
    *,
    detections: dict[str, Any],
    shots_payload: dict[str, Any],
    analytics: dict[str, Any],
) -> dict[str, Any]:
    final_shots = [final_shot_record(shot) for shot in shots_payload.get("shots", [])]
    detection_summary = {
        "tracked_classes": ["person", "racket", "ball"],
        "tracking_summary": detections.get("metadata", {}),
        "detections_count": detections.get("metadata", {}).get("detections_count"),
    }

    return {
        "assignment_requirements": {
            "detect_and_track": ["person", "racket", "ball"],
            "shot_types": ["forehand", "backhand", "serve_or_smash"],
            "structured_output_fields": ["shot_type", "timestamp", "frame", "player_track_id"],
            "visualization": "demo_video.mp4",
            "analytics": "analytics.json",
        },
        "metadata": shots_payload.get("metadata", {}),
        "detection_summary": detection_summary,
        "shot_summary": shots_payload.get("summary", {}),
        "analytics_summary": analytics.get("summary", {}),
        "shot_predictions": final_shots,
    }


def write_manifest(final_dir: Path, final_payload: dict[str, Any]) -> None:
    manifest = "\n".join(
        [
            "# Final Output Manifest",
            "",
            "This folder is generated by:",
            "",
            "```bash",
            "python -m src.run_pipeline",
            "```",
            "",
            "## Assignment Requirement Mapping",
            "",
            "- Detect and track players, racket, ball:",
            "  - `detections.json`",
            "  - `demo_video.mp4`",
            "- Classify 2-3 shot types:",
            "  - `shot_predictions.csv`",
            "  - `shot_predictions.json`",
            "- Include timestamp/frame/player in structured output:",
            "  - `shot_predictions.csv`",
            "  - `shot_predictions.json`",
            "- Demo visualization:",
            "  - `demo_video.mp4`",
            "- Shot count analytics:",
            "  - `analytics.json`",
            "  - `dashboard.png`",
            "",
            "## Current Summary",
            "",
            f"- Total shots: {final_payload.get('analytics_summary', {}).get('total_shots', 0)}",
            f"- Shot type counts: {final_payload.get('analytics_summary', {}).get('shot_type_counts', {})}",
            "",
        ]
    )
    (final_dir / "OUTPUT_README.md").write_text(manifest, encoding="utf-8")


def reset_final_dir(final_dir: Path) -> None:
    final_dir.mkdir(parents=True, exist_ok=True)
    for child in final_dir.iterdir():
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()


def finalize_outputs(outputs_dir: Path, final_dir: Path) -> None:
    phase1_video = outputs_dir / "annotated_phase1.mp4"
    phase2_video = outputs_dir / "annotated_phase2.mp4"
    detections_json = outputs_dir / "detections_phase1.json"
    detections_csv = outputs_dir / "detections_phase1.csv"
    shots_json = outputs_dir / "shots_phase2.json"
    analytics_json = outputs_dir / "analytics_phase3.json"
    dashboard_png = outputs_dir / "dashboard_phase3.png"

    for path in [
        phase1_video,
        phase2_video,
        detections_json,
        detections_csv,
        shots_json,
        analytics_json,
        dashboard_png,
    ]:
        require_file(path)

    reset_final_dir(final_dir)

    detections = load_json(detections_json)
    shots_payload = load_json(shots_json)
    analytics = load_json(analytics_json)
    final_payload = build_final_payload(
        detections=detections,
        shots_payload=shots_payload,
        analytics=analytics,
    )

    copy_required(phase2_video, final_dir / "demo_video.mp4")
    copy_required(detections_json, final_dir / "detections.json")
    copy_required(detections_csv, final_dir / "detections.csv")
    copy_required(analytics_json, final_dir / "analytics.json")
    copy_required(dashboard_png, final_dir / "dashboard.png")

    write_final_csv(shots_payload.get("shots", []), final_dir / "shot_predictions.csv")
    write_json(final_payload, final_dir / "shot_predictions.json")
    write_manifest(final_dir, final_payload)


def main() -> None:
    args = parse_args()
    finalize_outputs(args.outputs_dir, args.final_dir)
    print(f"Final output folder: {args.final_dir}")
    print(f"Demo video: {args.final_dir / 'demo_video.mp4'}")
    print(f"Shot predictions CSV: {args.final_dir / 'shot_predictions.csv'}")
    print(f"Shot predictions JSON: {args.final_dir / 'shot_predictions.json'}")


if __name__ == "__main__":
    main()
